app1/urls.py
from app1.views import *
from django.urls import path
app_name='app1'
urlpatterns = [

 path('dhoni/',dhoni,name='dhoni'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='app2'
urlpatterns = [
path('rohit/',rohit,name='rohit'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,'rohit.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>specific url mapping</h1>
    <a href="{% url 'app2:rohit' %}">navigate to rohit</a>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, consequuntur. Eveniet voluptatem repellendus aspernatur praesentium totam non soluta sint quisquam, iste id tempore. Natus voluptatem dolorem quisquam asperiores consequatur maxime?
    </p>
</body>
</html>

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>it is mombai indians team</h1>
   <a href=" {% url 'app1:dhoni' %}">navigate to dhoni</a>
   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem similique nostrum fuga ad accusamus ipsam tenetur quisquam iste molestias nam?</p>
</body>
</html>